help:
	    @echo "_______BUILD ANGULAR FRONTEND______\n"
	    @echo "To build all apps run make make build-frontend"

build-frontend:
	    ng build -a=0 &&\
	    ng build -a=1 &&\
			ng build -a=2 &&\
			ng build -a=3 &&\
			ng build -a=4 &&\
			ng build -a=5 &&\
			ng build -a=6 &&\
			ng build -a=7 &&\
			ng build -a=8 &&\
			ng build -a=9
